spring:
  application:
    name: Hoai Thuong
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
  servlet:
    multipart:
      max-file-size: 5MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - https://www.googleapis.com/auth/userinfo.email
              - https://www.googleapis.com/auth/userinfo.profile
              - https://www.googleapis.com/auth/spreadsheets
              - openid
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=consent&access_type=offline
auth:
  jwt:
    secret: ${JWT_SECRET}
cron:
  schedule:
    export-report: 0 0 16 * * *
server:
  compression:
    enabled: true
    mime-types: application/json
aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  bucket: ${AWS_BUCKET}