spring:
  application:
    name: Hoai Thuong
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
  servlet:
    multipart:
      max-file-size: 5MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - https://www.googleapis.com/auth/userinfo.email
              - https://www.googleapis.com/auth/userinfo.profile
              - https://www.googleapis.com/auth/spreadsheets
              - https://www.googleapis.com/auth/drive
              - https://www.googleapis.com/auth/calendar
              - openid
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=consent&access_type=offline
  cache:
    caffeine:
      spec: expireAfterAccess=60s
auth:
  jwt:
    secret: ${JWT_SECRET}
cron:
  schedule:
    export-report: 0 0 16 * * *
    sync-video: 0 30 16 * * *
    revoke-video-url: 0 30 17 * * *
server:
  compression:
    enabled: true
    mime-types: application/json
aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  bucket: ${AWS_BUCKET}
minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  access-secret: ${MINIO_ACCESS_SECRET}
  bucket: ${MINIO_BUCKET}
microsoft:
  tenant-id: ${MS_TENANT_ID}
  client-id: ${MS_CLIENT_ID}
  client-secret: ${MS_CLIENT_SECRET}
  drive-id: ${MS_DRIVE_ID}
drive:
  shared-folder: ${SHARED_DRIVE_FOLDER}